# Generated by Django 5.2.16 on 2026-07-12 15:25

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=comments.models.comment_file_path),
        ),
    ]
